language: objective-c
env:
  - TI_SDK=3.4.1.GA PLATFORM=ios
  - TI_SDK=3.4.1.GA PLATFORM=droid
  - TI_SDK=3.5.0.GA PLATFORM=ios
  - TI_SDK=3.5.0.GA PLATFORM=droid
script:
  - grunt "ci:$PLATFORM" "$PLATFORM" --sdk-version "$TI_SDK"
before_install:
  - npm install --global grunt-cli titanium
  - npm install
  - mkdir -p $HOME/.titanium
  - echo '{"loggedIn":true}' > $HOME/.titanium/auth_session.json
  - titanium sdk install "$TI_SDK" --no-progress-bars --no-prompt --no-banner --log-level info
